language: go

go:
  - "1.12.x"
  - master

os:
  - linux
  - osx

dist: trusty
install: true

script:
  - env GO111MODULE=on go get
  - env GO111MODULE=on go build
  - env GO111MODULE=on go vet
  - env GO111MODULE=on go test
